# In configuration.yaml
input_select:
  akkusteuerung_sma_wr:
    name: "Batterij Modus"
    options:
      - "Akku schnell Laden"
      - "Akku schnell Entladen"
      - "Akku Pause"
      - "Akku Automatisch"
      - "Akku 0.2C Laden"
    initial: "Akku Automatisch"

input_number:
  akkusteuerung_ladestaerke_soll:
    name: "Gewenst laadvermogen"
    min: 100
    max: 10000
    step: 100
    unit_of_measurement: "W"
    mode: slider
    
  akkusteuerung_entladestaerke_soll:
    name: "Gewenst ontlaadvermogen"
    min: 100
    max: 10000
    step: 100
    unit_of_measurement: "W"
    mode: slider
    
  akkusteuerung_02c_ladestaerke:
    name: "0.2C laadvermogen"
    min: 100
    max: 10000
    step: 100
    unit_of_measurement: "W"
    mode: slider

  akkusteuerung_wr_70proz_ueberschuss_grenze:
    name: "70% overproductie grens"
    min: 100
    max: 10000
    step: 100
    unit_of_measurement: "W"
    mode: slider

  akkusteuerung_wr_ac_ueberschuss_grenze:
    name: "AC overproductie grens"
    min: 100
    max: 10000
    step: 100
    unit_of_measurement: "W"
    mode: slider

  akkusteuerung_ab_welchem_restertrag_vollladen:
    name: "Minimale restopbrengst voor volladen"
    min: 1
    max: 100
    step: 1
    unit_of_measurement: "kWh"
    mode: slider

input_boolean:
  akku_opti_automatik:
    name: "Batterij optimalisatie automatisch"
    initial: off



sensor:
  - platform: template
    sensors:
      maximaler_ueberschuss_akkuladung:
        unique_id: maximaler_ueberschuss_akkuladung
        device_class: power
        state_class: measurement
        name: "Maximaal beschikbaar vermogen voor batterij laden"
        unit_of_measurement: W
        state: >-
          {{ (states('sensor.sn_3008959151_pv_power') | float) - 
             (states('sensor.sn_3008959151_metering_power_absorbed') | float) - 
             (states('sensor.sn_3008959151_battery_power_charge_total') | float) }}

      ueberschuss_pv_watt:
        unique_id: akkusteuerung_ueberschuss_pv
        device_class: power
        state_class: measurement
        name: "PV Overproductie"
        unit_of_measurement: W
        state: >-
          {{ (states('sensor.sn_3008959151_pv_power') | float) - 
             (states('sensor.sn_3008959151_metering_power_absorbed') | float) }}

      home_energy_usage:
        unique_id: home_energy_usage_w
        device_class: power
        state_class: measurement
        name: "Huisverbruik"
        unit_of_measurement: W
        state: >-
          {{ (states('sensor.sn_3008959151_metering_power_absorbed') | float) + 
             (states('sensor.sn_3008959151_grid_power') | float) - 
             (states('sensor.sn_3008959151_metering_power_supplied') | float)}}
    
